@startuml
title Smart House System User SaaS API Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(SmartHouseSystem, "Smart House System") {
   Container(WebApp, "Web Application", "React", "Web Application for the system")
   Container(UserService, "User SaaS API", "Python", "Provide User SaaS API") 
   Container(Database, "Database", "PostgreSQL", "Store system data")
}

Container(UserService, "User SaaS API", "Python") {
  Component(AuthController, "AuthController", "Handles authentication and authorization")
  Component(UserController, "UserController", "Manages user profiles")
  Component(SensorController, "SensorController", "Register user sensors")
  Component(ScenarioController, "ScenarioController", "Manage user scenario")
  Component(ServiceLayer, "Service Layer", "Business logic")
  Component(RepositoryLayer, "Repository Layer", "Data access logic")
}

Rel(WebApp, UserService, "Provide user service API")
Rel(AuthController,ServiceLayer,"Calls business logic")
Rel(UserController,ServiceLayer,"Calls business logic")
Rel(SensorController,ServiceLayer,"Calls business logic")
Rel(ScenarioController,ServiceLayer,"Calls business logic")
Rel(ServiceLayer,RepositoryLayer,"Reads/Writes data")
Rel(RepositoryLayer,Database,"Reads/Writes user data")
@enduml