@startchen

top to bottom direction

entity User {
  id : INTEGER <<key>>
  name : STRING
  login: STRING
  email: STRING
  isAdmin: BOOLEAN
}

entity House {
  id : INTEGER <<key>>
  userId : INTEGER
  address : STRING
}

relationship "owned-by" as OWNER {
}

OWNER -1- User
OWNER -N- House

entity SensorType {
  id : INTEGER <<key>>
  name : STRING
}

entity Sensor {
  id : INTEGER <<key>>
  houseId : INTEGER
  typeId : INTEGER
  serialNumber : STRING
  status : BOOLEAN
}

relationship "is-type-of" as ISTYPE {
}

ISTYPE -N- Sensor
ISTYPE -1- SensorType

relationship LOCATE {
}

LOCATE -1- House
LOCATE -N- Sensor

entity TelemetryData {
  id : INTEGER <<key>>
  sensorId : INTEGER
  data : STRING 
}

relationship GENERATE {
}

GENERATE -1- Sensor
GENERATE -N- TelemetryData

entity Scenario {
    id : INTEGER <<key>>
    userId : INTEGER
    startDate : DATE
    endDate : DATE
    active: BOOLEAN
}

relationship BUILD {
}

BUILD -1- User
BUILD -N- Scenario

entity ScenarioStep {
    id : INTEGER <<key>>
    sensorId : INTEGER
    script: OBJECT
}

relationship HAS {
}

HAS -1- Scenario
HAS -N- ScenarioStep

@endchen